### ISSUE TITLE
Current development available?

### ISSUE THREAD

**Issue by beniroquai** [braingeneers/images#37]
Hey, I'm curious if a newer version of this gui is available somewhere. I saw this in the README:

```current development happening at https://github.com/braingeneers/Picroscope-Image-Viewer-Dockerized```, but it seems that the link is dead. Would be great to see the code. Thanks :)

**Comment by pvbaudin** [comment]
The repo was private, I just changed it to public 
https://github.com/braingeneers/Picroscope-Image-Viewer-Dockerized

Although at this point, the functionality of this image viewer has been incorporated into and expanded in the DataHub website which can be found here:
https://github.com/braingeneers/Braingeneers-Datahub

**Comment by beniroquai** [comment]
Thanks a lot! I'll look into that! 
The GUI you wrote for this is running fully on AWS? Is the repo also available somewhere here? :)
